### ISSUE TITLE
[util] Create Pomodoro utility addin

### ISSUE THREAD

**Issue by DamianSuess** [xenoinc/ToolsHub#44]
pAs a user, I would like to have the [Pomodoro](https://github.com/xenoinc/Pomodoro) project converted to a utility add-in.

This add-in will serve as a Utility loader example

**Pull Request**: #69 

## Acceptance
* Migrate from standalone EXE to DLL
* Launch as an external add-in
* Load on startup as Utility

## Out of Scope
* Properties configuration to disable it
* Launch from SystemTray ExtensionPoint

## Tasks
* [X] Create add-in skeleton
* [x] System test updating SysTray icon
* [x] Update SysTray icon while running
* [x] Start/stop/pause working timer
* [x] Start/stop breaks
* [x] Tests
    * [x] Update SysTray icon while running
* [x] Preferences for timer settings
    * [x] Pomodoro times
    * [ ] Break times
    * [ ] Flash screen OnEvents
    * [ ] Send updates to NotificationIcon bubble
