### ISSUE TITLE
[pomodoro] Load Pomodoro as utility add-in

### ISSUE THREAD

**Issue by DamianSuess** [xenoinc/ToolsHub#74]
As a user, I would like to load the project [Pomodoro](https://github.com/xenoinc/Pomodoro) project as a utility add-in.

This add-in will serve as a Utility loader example

**Related to pull request**: #69 

## Acceptance
* Migrate from standalone EXE to DLL
* Launch as an external add-in
* Load on startup as Utility

## Out of Scope
* Properties configuration to disable it
* Launch from SystemTray ExtensionPoint

## Tasks
* [x] Create utility add-in handler
* [x] Strip-down Pomodoro.exe project
    * [x] Replace existing settings engine with ToolsHub's
    * [x] Remove Squirel packager
* [x] Preference
    * [x] Load utility from SysTray
    * [x] Load utility OnStart

**Comment by DamianSuess** [comment]
It's been decided to not load the Pomodoro add-in as a ``UtilityAddin`` but instead as a regular ``SysTrayAddin``.

Closing PBI and we'll make a series of stories apply the changes.
### See also:
#77 - Generate sounds
